# Generated by Django 4.2.1 on 2023-06-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_last_request_alter_myuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='profile_photo',
        ),
    ]
